export { hatchet } from "./client";
export { triggerScrapeHh } from "./triggers";
export type { GenerateResumeJobInput } from "./workflows/generate-resume";
export { generateResumeWorkflow } from "./workflows/generate-resume";
export type { HelloWorldInput } from "./workflows/hello-world";
export { helloWorldTask } from "./workflows/hello-world";
export type { ProcessDocumentInput } from "./workflows/multi-step";
export { processDocumentWorkflow } from "./workflows/multi-step";
export { scheduledWorkflow } from "./workflows/scheduled";
export type { ScoreResumeMatchesInput } from "./workflows/score-resume-matches";
export { scoreResumeMatchesWorkflow } from "./workflows/score-resume-matches";
export type { ScrapeHhInput } from "./workflows/scrape-hh";
export { scrapeHhWorkflow } from "./workflows/scrape-hh";
export { scrapeHhScheduledWorkflow } from "./workflows/scrape-hh-scheduled";
